# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
      paths:
        - 'digging-dashboard/frontend/**'
  pull_request:
      paths:
        - 'digging-dashboard/frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'digging-dashboard/frontend/package-lock.json'
        
    - name: Validate lockfile existence
      working-directory: ./digging-dashboard/frontend
      run: |
        if [ ! -f package-lock.json ]; then
           echo "❌ package-lock.json not found!"
           exit 1
        fi
        
    - name: ci
      working-directory: ./digging-dashboard/frontend/
      run: npm ci
    - name: build
      working-directory: ./digging-dashboard/frontend/
      run: npm run build --if-present
    - name: test
      working-directory: ./digging-dashboard/frontend/
      run: npm test
